version: '3'
services:
  user-mservice:
    container_name: user-mservice
    restart: on-failure
    build: ./
    ports:
      - '8080:8080'
    healthcheck:
      test: [ "CMD", "nc", "-z", "localhost", "8080" ]